dh:
  keycloak:
    serverUrl: http://localhost:8080/
    realm: master
    username: admin
    password: admin
    clientId: admin-cli
    clientSecret: CQ5HsXlLFftDzWyrsHYONKIfBJFr6v6X

server:
  port: 8084